### ISSUE TITLE
brunch-config.coffee file missing

### ISSUE THREAD

**Issue by marinaspas** [oddpixel/brunch-steak#1]
Hey I am wondering why this template doesn't have a brunch-config.coffee file that corresponds with the structure.

just wondering because I wanna learn what that config file would look like :) 

Thanks!

**Comment by oddpixel** [comment]
Hi Marina,

In the last commit I converted to the brunch-config.js config file as I prefer js over coffeescript.

You should be able to use the old config file in the previous commit here:
https://github.com/oddpixel/brunch-steak/blob/ed6a753699a4abe7c6fc4f98da587e4478fd4024/config.coffee

Hope that helps!

**Comment by marinaspas** [comment]
Thank you so much for replying :) 

yeah I do prefer the js version of this as well!
